export const BOOKS_LOADED = 'BOOKS_LOADED';
export const BOOK_ADDED_TO_CART = 'BOOK_ADDED_TO_CART';
export const BOOK_DELETED_FROM_CART = 'BOOK_DELETED_FROM_CART';
export const BOOK_REMOVED_FROM_CART = 'BOOK_REMOVED_FROM_CART';
export const BOOK_SET_LOADING = 'BOOK_SET_LOADING';
export const BOOK_SET_ERROR = 'BOOK_SET_ERROR';
